### ISSUE TITLE
Implement and test the Configuration class

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#103]
We need a Configuration class that will be used to store local configuration parameters as described in the [RunManager API](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst).  Flesh out the org.dataone.client.configuration.Configuration class in Matlab by implementing the set(), get() (inherited from hgsetget), loadConfig(), saveConfig(), and listConfig() methods.  Enable the class to also store dynamic properties (inherit from dynamicprops), so that scientists aren't limited to the pre-determined parameters per se. Test this class by creating an org.dataone.client.configuration.ConfigurationTest class that extends matlab.unittest.TestCase and exercises the methods.

**Comment by csjx** [comment]
@sycao5 - After our discussion on property value validation, I had thought about the format_id field, and how that can be problematic when the format identifiers used in system metadata aren't in the object format list.  You should be able to use the d1_libclient_java ObjectFormatCache to validate the format_id values being set.

**Comment by sycao5** [comment]
write it down.

**Comment by csjx** [comment]
@sycao5 - To finish out the Session class, we need to address the following functionality:
- [ ] Persistent sessions
  - When the Session() constructor is called, it should always call loadSession(path) with the default path location to the session file on disk.
  - The default path should work on any platform. On Mac/Linux, it should be `$USER/.d1/session.json`. On Windows it should be `%USERNAME%/.d1/session.json`.  In the event that `.d1` directory doesn't exist, create it. In the event it can't be created, throw an error.
  - For any call to set(session, name, value), we should be internally calling saveSession() in order to persist the changes.  
  - If the `session.json` file doesn't exist when the Session constructor is first called, we should call saveSession(path) to persist the new object after it is created.
- [ ] Support other Session locations
  - loadSession(path) should probably be a static method so an alternative session location could easily be loaded with `s = Session.loadSession('/my/alternate/session.json'`. In this case, we might need to add and set a property that holds the session file location so that subsequent changes to this session object get persisted to the correct file during calls to saveSession(path).
- [ ] Session file format
    - The session can be stored as JSON. Although Matlab doesn't natively support JSON, the [JSONLab](http://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files-in-matlab-octave) library looks to be a stable solution. Also see http://undocumentedmatlab.com/blog/json-matlab-integration.
  - Add the JSONLab library into github in `matlab-dataone/lib/matlab` and add the licensing information into the top level Readme file.  We should also evaluate the license terms to make sure it is compatible and distributable.
- [ ] Viewing Session parameters
  - The listSession() method needs to be implemented, which displays the session object. I'm not sure that this is super useful since Matlab will display a Session `s` just by typing `s`, but we could provide a nicely formatted list. Seems like lower priority though.
- [ ] Testing
  - Each of the API methods need unit tests to ensure they work as advertised.

**Comment by sycao5** [comment]
Get it

**Comment by sycao5** [comment]
One question for default path for persistent_session_storage_path. $USER and %USERNAME% are for account name. Then what is the full path for persistent_session_storage_path?

Thanks !

**Comment by csjx** [comment]
@sycao5 -I see what you mean - I think I mis-wrote it above.  On Mac/Linux, it will be `$HOME/.d1/session.json`, and on Windows it would be `%USERPROFILE%\.d1\session.json`. See https://en.wikipedia.org/wiki/Environment_variable#Windows if needed.
