### ISSUE TITLE
Use YesWorkflow classes to generate provenance statements from the Matlab RunManager

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#105]
@sycao5 - Hi Yang,
As we discussed with Tim (@tmcphillips), we plan to use the YesWorkflow library to generate prospective provenance information about a Workflow, and to incorporate the triples as RDF statements in an DataONE resource map that will be uploaded to a Member Node using the Matlab RunManager's publish() method.  We also discussed producing a workflow graphic showing the script workflow, which I've written up in #106.  For generating the ProvONE statements:
- [x] From within the RunManager, call the YesWorkflow extractor to extract comments and produce a triple map
  - The map should be of the form Map&lt;Predicate, Map&lt;Identifier, List&lt;Identifier&gt;&gt;&gt; where a Predicate is associated with a Map consisting of an Identifier (the subject of the triple) and a List of Identifiers (the objects of the triples)
  - The tripleMap should contain the following YW-derived statements
    - `provone:Program provone:hasOutPort provone:Port` (where the `Program` is the URI to the scientific script, and the `Port` is the URI to the same script, but appended with the variable name extracted from the `@out` YW comment). E.g. `https://cn-sandbox-2/cn/v1/resolve/script_id.m#output_variable_name`
    - `provone:Program provone:hasInPort provone:Port` (where the `Program` is the URI to the scientific script, and the `Port` is the URI to the same script, but appended with the variable name extracted from the `@in` YW comment). E.g. `https://cn-sandbox-2/cn/v1/resolve/script_id.m#input_variable_name`
- [x] Add each triple statement to the DataPackage instance in the RunManager using the `insertRelationship()` method.
- [x] Write an `org.dataone.client.run.YesWorkflowTest` in the Matlab DataONE Toolbox that:
  - Uses one of the MsTMIP example scripts marked up with YW comments
  - Calls the RunManager record() method with the script as input
  - Ensures that the resulting DataPackage instance from the run contains the correct provenance triples

**Comment by tmcphillips** [comment]
It sounds like the first iteration of this feature will need access only to the YW annotations on the top-level block of a program or script marked up with YW comments.  (The `provone:Program` identifiers in the triples will be URIs to the script as a whole, the `provone.Port` identifiers all will be same script URI qualified with fragment identifiers derived from the port variable names, and there will be no triples using the `provone:hasSubProgram` predicate.

If this is correct, then retrieving the needed info from a script using YW can be as simple as creating a BufferedReader to access the script source...

    BufferedReader reader = new BufferedReader(new StringReader(
                "    %  @begin script           " + EOL +
                "    %  @in x @as horiz         " + EOL +
                "    %  @in y @as vert          " + EOL +
                "    %  @out d @as dist         " + EOL +
                "                               " + EOL +
                "    some Matlab code           " + EOL +
                "                               " + EOL +
                "    % @end script              " + EOL
    ));

 extracting the YW annotations from the source...

    LanguageModel lm = new LanguageModel(Language.MATLAB);
    List<Annotation> annotations = new DefaultExtractor()
                                       .languageModel(lm)
                                       .source(reader)
                                       .extract()
                                       .getAnnotations();

...building a workflow model of the script:

    Program program = new DefaultModeler()
                          .annotations(annotations)
                          .model()
                          .getModel();

...and finally retrieving the in and out ports of the top level program:

    Port[] inPorts = program.inPorts;
    Port[] outPorts = program.outPorts;

The "binding" (i.e. the alias on the port if the `@as`keyword was used, else the actual variable name) for each port can be accessed via the `flowAnnotation` property on each port:

    assertEquals(2, inPorts.length);
    assertEquals(1, outPorts.length);
    assertEquals("horiz", inPorts[0].flowAnnotation.binding());
    assertEquals("vert", inPorts[1].flowAnnotation.binding());
    assertEquals("dist", outPorts[0].flowAnnotation.binding());

**Comment by sycao5** [comment]
Hi Chris and Tim,
I add five jars to matlab javaclasspath. They are listed as below. Please verify it.

hamcrest-core-1.3.jar
jopt-simple-4.8.jar
junit-4.11.jar
snakeyaml-1.13.jar
yesworkflow-0.2-SNAPSHOT.jar

**Comment by sycao5** [comment]
I experiment to add above to matlab javaclasspath.txt which includes yesworkflow.jar and first-level dependency libs. The test shows that Matlab cannot access yesworkflow java class. I guess we should find all recursive dependency libs and add them to the javaclasspath.

**Comment by tmcphillips** [comment]
If you expand the YW jar that includes dependencies you will see what is actually needed to run YesWorkflow.  The junit and hamcrest libraries are not there, so I think the snakeyaml and jopt-simple jars are the only indirect dependencies at run time. I suggest looking at the error you get and seeing if the missing class is or is not in these jars.

**Comment by tmcphillips** [comment]
I just tried running the sample code I provided above in a unit test that I added to a local checkout of d1_libclient_java. (I know this is not where we want to place the dependency on YW. I'm just doing this to exercise the dependency resolution mechanism in a relevant context.)

I first deleted the yesworkflow directories and artifacts from my local ~/.m2/repository, and confirmed that d1_libclient_java would not build due to the missing dependency on yesworkflow.  I then added two elements to the pom.xml for d1_libclient_java. 

Inside the `<dependencies>` element I placed:
    
    <dependency>
        <groupId>org.yesworkflow</groupId>
        <artifactId>yesworkflow</artifactId>
        <version>0.2-SNAPSHOT</version>
    </dependency>

And inside the `<repositories>` element I placed:

    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>

The d1_libclient_java build (`mvn package`) then succeeded, and the new test passed.  The target/lib subdirectory now contains yesworkflow-0.2-SNAPSHOT.jar and jopt-simple-4.8.jar (it did not before).  I am investigating why snakeyaml jar is not present....

**Comment by sycao5** [comment]
Import D1 class:
>> import org.dataone.client.v2.formats.ObjectFormatCache;
>> import org.dataone.configuration.Settings;

Import YW class:
>> import org.yesworkflow.LanguageModel;
Error using import
Import argument 'org.yesworkflow.LanguageModel' cannot be found or cannot be imported.

I use LanguageModel class in the test code using following statements:           
%% Test for YesWorkflow
import org.yesworkflow.LanguageModel;
lm = LanguageModel(Language.MATLAB);

**Comment by sycao5** [comment]
For your reference,

http://undocumentedmatlab.com/blog/java-class-access-pitfalls

**Comment by tmcphillips** [comment]
Is `org.yesworkflow.LanguageModel` in the jar that you are using?  Here's what I find in the `yesworkflow-0.2-SNAPSHOT.jar` retrieved automatically from the snapshot repository by maven:

    $ jar -tvf yesworkflow-0.2-SNAPSHOT.jar  | grep LanguageModel
      1212 Mon Mar 23 14:16:36 PDT 2015 org/yesworkflow/LanguageModel$1.class
      1499 Mon Mar 23 14:16:36 PDT 2015 org/yesworkflow/LanguageModel$Language.class
      1291 Mon Mar 23 14:16:36 PDT 2015 org/yesworkflow/LanguageModel$MatchExtent.class
      5290 Mon Mar 23 14:16:36 PDT 2015 org/yesworkflow/LanguageModel.class

**Comment by tmcphillips** [comment]
I removed an unneccesary <optional> tag from the snakeyaml dependency declaration in the YesWorkflow pom.xml file, deployed a new snapshot, and now snakeyaml-1.13.jar appears in the d1_libclient_java/target/lib directory after `mvn package`.  I suspect this issue was unrelated to the problem under discussion, however, because the test exercising the YW API was already working (perhaps because snakeyaml isn't used if the CLI isn't employed).

**Comment by sycao5** [comment]
Hi Tim

Here is the github link for maklab-dataone: https://github.com/DataONEorg/matlab-dataone
Thanks.

**Comment by sycao5** [comment]
I download YesWorkflow from Maven central. If I add the snapshot.jar to the static class path, YW classes can not be found. But when I add the jar to the dynamic path, the classes can be access now.

cheers,

Yang

**Comment by sycao5** [comment]
I am still waiting for a decision on whether we need a triple map output from yesWorkflow Extractor.
