### ISSUE TITLE
Use YesWorkflow classes to generate a workflow graphic from the Matlab RunManager

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#106]
@sycao5 Hi Yang,
From our conversation with Tim (@tmcphillips), we plan to use the YesWorkflow library to generate a graphic of a scripts workflow as it is documented in the YW comment syntax.  To do this:
- [x] Add a Session property `generate_workflow_graphic` with a default of `false`
- [x] In the RunManager, determine if we should generate the graphic based on the setting
  - If so, use the YW graph class to generate the graphic from the YW Model produced from YW Extract
- [x] Add another Session property called `include_workflow_graphic` with a default of `false`
- [x] In the RunManager, determine if we should include the workflow graphic as an object in the DataPackage based on the session property
  - If so, create a `D1Object` of the graphic, and use the `addData()` method to add it to the DataPackage
- [x] Write an `org.dataone.client.run.YesWorkflowTest` in the Matlab DataONE Toolbox that: 
  - Uses one of the MsTMIP example scripts marked up with YW comments
  - Calls the RunManager record() method with the script as input
  - Ensures that the resulting DataPackage instance from the run contains the graphic image as a member

**Comment by sycao5** [comment]
complete step 1-3; but the graphic image file names are hardcoded which needs to change
