### ISSUE TITLE
Resolve Java library conflicts in the Matlab DataONE Toolbox

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#110]
During initial development we've noticed that some of the libraries that we add to the Java classpath in Matlab conflict with older versions of the same libraries that ship with Matlab.  For instance, in Matlab 2014a, the Apache `http-core` jar needed for the d1_libclient_java library to function conflicts with the `http-core` jar shipped with axis2 in Matlab. This conflict doesn't show in R2014b.
Determine what versions of Matlab we will support (back to,say, 2012??) and resolve the conflicts. Manual strategies include overriding classes with a `<before>` line in the local javaclasspath.txt file or commenting out the older libraries in the shipped classpath.txt file, but these are on a per-installation basis(and may be too technical for some users).  Explore changing the classpath programmatically. See https://stackoverflow.com/questions/16366059/best-way-to-override-matlabs-default-static-javaclasspath

**Comment by sycao5** [comment]
The number of objectFormat list I got is still 94 which is not consistent with the current total number of object Format which is 109. This maybe another issue need to troubleshoot.

**Comment by csjx** [comment]
To deal with library conflicts, we've created an installer script that adds the `javaclasspath.txt` file in place with the `<before>` keyword so our libraries are loaded before those that ship with Matlab.  All are on the static Java classpath.  This needs testing on multiple OSs, but we'll add another ticket for that, since the conflicts are resolved.
