### ISSUE TITLE
create SOLR version of semantic queries in use case 52

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#111]

**Comment by SophieHou** [comment]
This issue is related to #119

**Comment by mobb** [comment]
From notes:

Target 3 types of queries for each plain-english query:
   1) Best SOLR nat lang fields query from UI fields available
        - ONEMercury
        - MetacatUI (search.test.dataone.org)
   2) Best SOLR nat lang fields query using any fields
         (attributeName|attributeLabel|attributeDescription = soil* AND attributeUnits = *gram AND abstract|title|methods = hetertroph*)
   3) Best semantic fields query

**Comment by mobb** [comment]
added 2 files: 
https://github.com/DataONEorg/semantic-query/blob/master/lib/queries/uc52_query_frags_best_SOLR.csv
and
https://github.com/DataONEorg/semantic-query/blob/master/lib/queries/uc52_query_frags_metacatUI.csv

Not sure if SOLR syntax is correct; will need advice.
