### ISSUE TITLE
Execute first precision / recall test round

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#119]
Coordinate all tasks and run the first tests with all 10 sample queries on Test Corpus C.

- Target: June 1, 2015

**Comment by SophieHou** [comment]
This issue is related to #121

**Comment by SophieHou** [comment]
The original 10 sample queries are in the following link: https://github.com/DataONEorg/sem-prov-design/blob/master/docs/use-cases/semantics/use-case-52-Semantic-Search.rst

**Comment by SophieHou** [comment]
This issue is also related to #111
