### ISSUE TITLE
Edit textual ProvONE spec for accuracy and completeness

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#125]

**Comment by sycao5** [comment]
@csjx @mbjones 

Can we close this issue now? If not yet, what the remaining or any difficulty need to complete or solve?

**Comment by csjx** [comment]
@sycao5 I've looked at the HTML specification again, and while it is accurate with regard to the newest ProvONE model, I don't think it is fully complete.  In particular, we've added a number of new classes and predicates, but they are lacking examples.  For specifications like these, having a Turtle example of each makes it much more understandable.  The missing examples should build on the examples already in the document.  Yang, will you take a pass at that?

**Comment by sycao5** [comment]
I can work on this issue too. thanks

**Comment by sycao5** [comment]
The latest version is at: 
https://github.com/DataONEorg/provweek2016-demo/blob/master/ProvONE-spec-revisit-2016/The%20ProvONE%20Data%20Model%20for%20Scientific%20Workflow%20Provenance.html

Section 3.3 needs three more examples.

**Comment by sycao5** [comment]
This task has been completed. So I close it now.
