### ISSUE TITLE
fix bug where index values get mangled

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#126]
See redmine ticket.

**Comment by leinfelder** [comment]
Are talking about this one? https://redmine.dataone.org/issues/6800

**Comment by mbjones** [comment]
Yep that's it.

**Comment by lauren-walker** [comment]
I just updated the redmine ticket with an example ID that is experiencing this issue now. I hope that helps with debugging.

**Comment by csjx** [comment]
The fix here is to move to Solr 5, since this seems to be a Solr bug. Solr 5 is deployed to cn-sandbox-ucsb-2, so I'm going to close this issue.
