### ISSUE TITLE
resolve multi-graph SPARQL query issue

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#127]
Need to query across graphs from multiple resource maps.

Do we need all ORE files loaded in the graph? Or just one hop?

If all, then likely need triple store.

Needed to complete the UI work, but can start UI testing before this is complete.

**Comment by leinfelder** [comment]
If we went with a persistent triple store, is worry about a few things:
- size of the store getting out of hand
- [incorrectly] assuming every ORE model you need is loaded at the time you issue the query  

There's really no guarantee about other referenced content being processed in a certain order which may make an explicit query across known (and loaded) graphs more suitable. And would hopefully buffer us from growing too large. 

At any rate, I think we can quite easily experiment with a couple different approaches and add checks to prevent us from doing an infinite loop when including graph dependencies.

**Comment by leinfelder** [comment]
Task not applicable for current architecture
