### ISSUE TITLE
ESOR JSON response

### ISSUE THREAD

**Issue by leinfelder** [DataONEorg/sem-prov-design#134]
Queries to ESOR that include quotes are returning invalid JSON (quotes are not escaped)
For example, this:
http://dataonetwc.tw.rpi.edu/linkipedia/search?query=carbon%20%22including%20raw%20quotes%22%20in%20response

Returns:
{"query": "carbon "including raw quotes" in response","time": "0.0","num_result": "1","results": [{"url": "","score": "0.0"}]}

But should be:
{"query": "carbon \"including raw quotes\" in response","time": "0.0","num_result": "1","results": [{"url": "","score": "0.0"}]}

ESOR should return valid JSON with all special characters escaped as needed.

**Comment by XixiLuo** [comment]
I find the problem too. I will let you know when I update code in github.

**Comment by XixiLuo** [comment]
fixed.
