### ISSUE TITLE
Implement and test the RunManager publish() method

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#135]
The `publish()` method is defined in the [Run Manager API](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst), and takes a `DataPackage` argument (to be uploaded) and a Client argument (the `D1Client` instance used to make the Member Node calls). To implement this method:
- [x] Add an `authentication_token` property to the Configuration class
- [x] When a scientist calls `set(config, authentication_token)`, handle this call by setting the property, and returning a warning message that says: *"Your authentication token has been set in your configuration file.  Please be careful to safeguard this token.  Anyone with access to it can call operations as you.  Be careful to not add this token to any published scripts, but rather set it only using a command prompt. This token will expire at {add the expiration time from the token here}.  Please log in again and set the token again after it expires."*
- [x] When a token is set, read the token's properties and set the `submitter`, `rights_holder`, and `foaf_name` properties using the Subject DN encoded in the token.
- [x] For each D1Object in the DataPackage, reserve an identifier using the CN.reserveIdentifier() method.
- [x] Ensure the system metadata associated with each D1Object is correct from the Configuration properties (see above), but also include the `AccessPolicy` and `ReplicationPolicy`
- [x] Upload each object (and the resource map) using the MNStorage.create() method.  Handle upload errors with helpful messages to the scientist.
- [x] Write a RunManager test to exercise the `publish()` method.

**Comment by mbjones** [comment]
This looks great, @csjx.  As I said on our call, for the R client I think this probably doesn't belong in `recordr`, but rather in `rdataone`. As those are combined in Matlab, it isn't an issue there.

**Comment by sycao5** [comment]
I have tried the new insertRelationship() in matlab code. The intermittent failure issue is fixed. Thanks. One strange issue is that the resourceMap generated using d1_libclient_java library can have prov and provone statements (see ProvResourceMapBuilderTest.java). But the resourceMap generated from matlab has no prov and provone statements although we have used the insertRelationship() in the program.

**Comment by sycao5** [comment]
I find that there are two different CN resolve URI base in the generated resourceMap. The prefix for D1 identifier is https://cn.dataone.org/cn/v1/resolve/, but the prefix for URI is https://cn-sandbox-2.test.dataone.org/cn/v1/resolve/. Please check the example resourceMap at https://github.com/DataONEorg/matlab-dataone/blob/master/src/test/resources/runs/30e572c6-7764-4ac4-b32a-f796ca30bd8a/resourceMap_C3_C4_map_present_NA_Markup_v2.xml 

This issue may need some attention. Thanks

**Comment by sycao5** [comment]
I still do not know how to use the function CN.reserveIdentifier() and MN.create(). The error information is attached below.
 Could not create member node reference: Java exception occurred: 
    org.dataone.service.exceptions.ServiceFailure: Unknown error, status = false
    	at org.dataone.service.util.ExceptionHandler.deserializeXml(ExceptionHandler.java:633)
    	at org.dataone.service.util.ExceptionHandler.deserializeXmlAndThrowException(ExceptionHandler.java:517)
    	at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:363)
    	at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:313)
    	at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:107)
    	at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:82)
    	at org.dataone.client.rest.HttpMultipartRestClient.doPostRequest(HttpMultipartRestClient.java:448)
    	at org.dataone.client.v2.impl.MultipartMNode.create(MultipartMNode.java:530)

**Comment by mbjones** [comment]
Can you paste in the XML that is returned as the error message? That stack trace is only of the client error handler, and so doesn't show the server-side error that actually occurred.

**Comment by sycao5** [comment]
The  REST post request is attached below.
 
[INFO] RestClient - rest call info: POST https://mn-demo-5.test.dataone.org/knb/d1/mn/v2/object; MMP message has: ParamPart:pid = pubTest_ywExtractFacts.pl; FilePart:object = /var/folders/q4/c9mphbxn17jcyvm9f1ykp5200000gn/T/mmp.output.8638964585666659884.tmp (5560 bytes); FilePart:sysmeta = /var/folders/q4/c9mphbxn17jcyvm9f1ykp5200000gn/T/mmp.output.3607767510290994406.tmp (872 bytes);

**Comment by mbjones** [comment]
That still doesn't show the XML error message that the client got back.  You may need to use a debugger to stop execution at org.dataone.service.util.ExceptionHandler.java:633 when processing the Exception so you can see it.

**Comment by csjx** [comment]
The `testPublish()` function in the RunManagerTest class is commented out, and it also doesn't test the success of the `publish()` function using assertions.  This needs to be fixed. Reopening.
