### ISSUE TITLE
Implement and test a private RunManager saveExecution() method

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#143]
- [x] Create a private saveExecution() function in the RunManager class that writes the results of an execution to the specified provenance storage directory.

  * Execution results should be saved in two locations:
    1) A new directory named with the execution_id should be created in a `runs` directory within the directory designated in the `provenance_storage_directory`.  The DataPackage and all of its artifacts should be saved to this directory.

    2) The summary of each execution should be appended to an executions database, a CSV file named `runs.csv` in the provenance_storage_directory with the following columns: 
      * runId - the assigned identifier of the run
      * tag - the tag (string label) associated with the run
      * software_application - the full path to the script or model being run
      * startTime - the start time of the run in UTC time (YYYYMMDD-HHMMSS.sss)
      * endTime - the end time of the run in UTC time (YYYYMMDD-HHMMSS.sss)
      * publishedTime - the publish time of the run in UTC time (YYYYMMDD-HHMMSS.sss)
      * packageId - the identifier of the ORE package associated with the run
      * errorMessage - any error message that was raised during the run
  
  Populate these fields from the Execution instance created in the RunManager. If the file hasn't been created yet, create it with just the column headers before appending to it. See https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst#listruns.

- [x] Create a unit test that exercises the saveExecution() function.

**Comment by sycao5** [comment]
OK

**Comment by csjx** [comment]
Yang wrote:
> The current implementation of the saveExecution() function is from line 499 at 
> https://github.com/DataONEorg/matlab-dataone/blob/master/src/matlab/%2Borg/%2Bdataone/%2Bclient/%2Brun/RunManager.m
> 
> and the generated executions.csv is at 
> 
> https://github.com/DataONEorg/matlab-dataone/blob/master/src/test/resources/executions.csv
> 
> My current difficulty is that I am not familiar with matlab and how to manipulate 
> the matrix and cell array. So my implementation takes longer time. I am trying to 
> move faster. If you and Chris have good reference for matlab matrix and 
> cell array manipulation, please let me know.

Yang, Matlab has two functions to deal with CSV data called `csvwrite` and `csvread`.  However, these don't handle mixed-type cell arrays (just uniform matrices), so Matlab suggests you use either `fprintf` (as you are doing) or `writetable` to create CSV files.
While I think your approach is fine with `fprintf`, you'll need to be careful with strings that contain the field delimiter (a comma), since they'll break the column count.  So, your function should escape strings by putting them into quotes.  Have a look at this [Matlab](http://www.mathworks.com/help/matlab/import_export/write-to-delimited-data-files.html) page for details.

**Comment by sycao5** [comment]
Thanks !

**Comment by csjx** [comment]
Oh, and Yang, when I get a chance, I'll look at your array manipulation code with regard to `listRuns()` etc.

**Comment by mbjones** [comment]
Question: are the date columns in the file compliant with ISO 8601? I'd argue they should be, but seems they may not be.

**Comment by sycao5** [comment]
I used "detester" to generate the matlab date format (type 30). So the date columns is ISO 8601, but it is not UTC time.

datestr 30 (ISO 8601)  'yyyymmddTHHMMSS'        20000301T154517

**Comment by sycao5** [comment]
Question:   The DataPackage class has getMetadataMap() method now. Then, how to get the the packageMap (Map<Identifier, Map<Identifier, List<Identifier>>>) from a resourceMap? The view(packageId) method need the packageMap to interpret the data package.

**Comment by sycao5** [comment]
In order to parse the triples contained in a resourceMap, I use Jena to read the rdf file into a model. Then, for a given predicate like "wasGeneratedBy", the related subject list with this property in the resourceMap.rdf can be found. Next, the returned subject list can be used by the view(packageId) function. 

The current issue I ran into is that when matlab passes the resouceMap path (relative or full path) to the com.hp.hpl.jena.util.FileManager to load the model or open the rdf file. The file can not be found. The file can be accessed in the java environment.

**Comment by sycao5** [comment]
The white space should be removed first before passing it to the java function call, like this:

 resMapFileName = strtrim(ls('*.rdf'));

**Comment by csjx** [comment]
There is a `saveExecution()` function in the RunManager class, but there's not a RunManagerTest unit test that exercises this function and makes assertions about the success of the function.  Reopening.

**Comment by csjx** [comment]
Given that saveExecution() is a private function, we won't be able to unit test it.  Closing again.
