### ISSUE TITLE
Change the RunManager class based on reviewed items

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#144]
After reviewing the RunManager changes that Yang implemented, I have some suggested changes that will keep the code cleaner and more production-oriented.

- [X] change configYesWorkflow() to be a private function

- [X] change getCertificate() to be a private function

- [X] change captureProspectiveProvenanceWithYW() to be a private function

- [X] In startRecord(), `CN_URL`, `D1_URI_PREFIX`, `aTypePredicate`, `associationSubjectURI`, and `execURI` etc. shouldn't be declared global.  It would be cleaner to set them as member varialbles

- [X] The `D1_URI_PREFIX` shouldn't end in a '/' (only by convention).  Fix this so that the REST endpoints start with '/'.

- [X] Change variables such as `k`, `E`, etc. to something meaningful (keep the code transparent)

- [X] Remove all hardcoded prefixes and suffixes from the code.  These should be part of the configuration at a minimum. Like:
```matlab
runManager.wfMetaFileName = [runManager.configuration.script_base_name '_meta1.1'];
```
- [X] Refactor endRecord()
* The method is too long and has too many implementation details.  Refactor it to call private functions that do the work.
* Remove the global variable declarations
* Move the YesWorkflow code into a private generateYesWorkflowGraphic() function
* Ensure that the image generation works on all platforms (Windows doesn't work)  
* Create a private buildPackage() function to encapsulate all of the calls to insertRelationship()
* Only print debug messaging if debug == true

**Comment by sycao5** [comment]
Hi Chris,
Thank you for your advice!
Yang

**Comment by csjx** [comment]
@sycao5 
Yang, after reviewing the code, it looks to me like you've addressed all of these points.  Please add comments to tickets as you work through them or finish them so it's easier to tell what you've done.  I'll close this ticket, but please close others as you complete them too.  Thanks!
