### ISSUE TITLE
Factor out extra tests in RunManagerTest.testInstanceWithConfiguration()

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#154]
Our unit tests should be as atomic as possible.  Remove the YesWorkflow testing from this test, and create a new unit test that tests the YesWorkflow functionality.

**Comment by sycao5** [comment]
Create a new function testYesWorkflow( ) in RunManagerTest.m; add a new public function callYesWorkflow(scriptPath, dirPath) which is a wrapper of three calls to yesWorkflow in RunManager.m

**Comment by csjx** [comment]
While there is a `testYesWorkflow()` function in RunManagerTest, it is commented out, and it doesn't make any assertions about the success of the call() to `callYesWorkflow()`.  This needs to be fixed. Reopening.

**Comment by sycao5** [comment]
Done!
