### ISSUE TITLE
Overload I/O functions with wrapper functions

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#156]
Overload I/O functions with wrapper functions in order to capture I/O calls prior to them being executed so we can record their provenance. These functions should be orgainzed in the [io](https://github.com/DataONEorg/matlab-dataone/tree/master/src/matlab/overloaded_functions/io/) directory.  Use the [ncread](https://github.com/DataONEorg/matlab-dataone/tree/master/src/matlab/overloaded_functions/io/netcdf/ncread.m) function as an example.  Overload the following, in this order of priority:
- [x] ncread, ncwrite
- [x] csvread, csvwrite
- [ ] load, save
- [x] DataONE API get(), create(), update()
- [x] dlmread, dlmwrite
- [x] cdfread, cdfwrite
- [x] hdfread, hdfwrite
- [x] h5read, h5write
- [x] textread
- [ ] textscan
- [x] readtable, writetable
- [x] xlsread, xlswrite
- [x] imread, imwrite
- [x] fitsread, fitswrite
- [x] multibandread, multibandwrite
- [x] xmlread, xmlwrite

The plan is to manipulate the Matlab path to be sure these functions get called in lieu of the shipped functions, provenance is captured, and then the overloaded functions are removed from the Matlab path prior to calling the original I/O function.  Once the result is complete, put the overloaded functions back on the Matlab path.  Using builtin() doesn't work for most of these functions, hence the path gymnastics.

Write a unit test that exercises each overloaded function and ensure that it creates the appropriate provenance statements in the RunManager.dataPackage, and that it executes the original I/O function call correctly.

**Comment by csjx** [comment]
After discussion with Peter and Yang, we've decided to try a strategy of setting and getting a provenance capture flag instead of removing individual functions from the path. Create a RunManager.setProvenanceCapture() function that takes a boolean true/false.  If it is set to false, all wrapper functions will be removed from the path.  If true, they'll all be added to the **top** of the path.

**Comment by sycao5** [comment]
what is the data object format should be used for load( ) function?

**Comment by csjx** [comment]
We don't have a Matlab .mat object format yet, but that would be the correct format.  we'll need to add it to the format list (and determine what the formatId should be).

**Comment by csjx** [comment]
@sycao5 - As you work on the rest of these functions, note that each overloaded function needs to refer to the following RunManager.configuration properties to determine if we capture I/O provenance or not:
- capture_file_reads
- capture_file_writes
- capture_dataone_reads
- capture_dataone_writes

So, you'll need some logic for that.  Note that I've added the DataONE API calls above.
Also, please wrap any disp() calls with
```matlab
if ( configuration.debug )
    disp('your message here');
end
```
This will keep the scientist from having to see command output unless they are really interested.

**Comment by csjx** [comment]
@sycao5 - Since `load()` and `save()` are I/O functions, please move the overloaded versions to a `matlab-dataone/src/overloaded_functions/io/builtin` directory.

**Comment by sycao5** [comment]
After implementing the `load()` function, we’re having problems with builtin datasets, like using 
``matlab
`load(‘coast’)`, `load(`topo`)`, `load coast`, `load topo`
```

We need to address this issue.

**Comment by csjx** [comment]
For overloading the DataONE API calls, we may need to overload the `d1_libclient_java` classes themselves.  For instance, in Matlab, if the following is called in a script:
```matlab
import org.dataone.client.v2.itk.D1Client;
mn = D1Client.getMN('urn:node:XXXX');
datafile = mn.get(id);
```
then we will likely need to create classes for D1Client and MNode.  This needs some investigation.

**Comment by sycao5** [comment]
Outstanding task: to download the url data as a local copy, for example, ncread(url)

**Comment by sycao5** [comment]
There is a problem for current netcdf.create( ). A D1 object is created and its system metadata are set in the modified netcdf.create( ). But the actual file size of this newly created file is unkown at the end of netcdf.create( ) function.

**Comment by sycao5** [comment]
Temporarily use 'application/netcdf' as object format for the 'common data format file' which may not be correct because netcdf is 'Network Common Data Format '

**Comment by sycao5** [comment]
Read/write data from HDF5 data set, we have the following options:
1. hdfread, hdfwrite(not available)
2. h5create, H5D.create, H5D.write, h5disp, h5read, h5writeatt 
3. hdf5info, hdf5read, hdf5write (will be removed in a future version)

Need to an object format type for HDF data

**Comment by csjx** [comment]
Hi Yang,
For a default object format, you can use `application/octet-stream`.  There is no `application/netcdf` object format (those should be `netCDF-3` or `netCDF-4`.  I'll put a ticket in and add object formats for the HDF file types.  Thanks for pointing this out.

**Comment by sycao5** [comment]
The functions xlsread and xlswrite are not working on mac OS.

**Comment by sycao5** [comment]
Need to find examples (advanced use) for xmlread( ) and xmlwrite( ) because URL, URN can be used in the case of advanced use.

**Comment by sycao5** [comment]
Need to track down `load()` and the `dot` issues

**Comment by csjx** [comment]
I'm closing this issue. See #202 for further work.
