### ISSUE TITLE
Develop a unit test for record() 

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#159]
The record() method has no unit test yet.  Write a test that ensures that a script is run, it's metadata are recorded, and that all prov statements are captured correctly in the RunManager.dataPackage.

**Comment by sycao5** [comment]
Completed !

**Comment by csjx** [comment]
The current head has a `testRecord()` method that is commented out, and the method doesn't test an assertions that the call to `record()` succeeded.  This needs to be fixed. Reopening.

**Comment by sycao5** [comment]
Done.
