### ISSUE TITLE
Modify RunManager to include the timezone offset in formatted dates

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#160]
Include the timezone offset in formatted dates using datestr() or other functions that include the timezone  (e.g. 20150828T042455+0060)

**Comment by sycao5** [comment]
use  datetime to format the dates including timezone 

Eg: datetime( 'now', 'TimeZone', 'local', 'Format', 'yyyy-MM-dd HH:mm:ssZ'  );
