### ISSUE TITLE
Enable provenance tracking for interactive commands

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#161]
startRecord() and endRecord() need to be aware of the interactive session, and should record command line commands that are file-level i/o commands.

**Comment by sycao5** [comment]
Algorithms for the interactive mode

Assume: 
 1. I/O functions are added to the project path. So the provenance can be captured through I/O function calls. 
 2. A user can call the function startRecord( ) and endRecord( ) to indicate the starting point and the ending point of an interactive session.

In startRecord( ):
--------------------------------

if runManager.recording == false:
    step 1. Set runManager.recording = true because  we are in interactive mode now. 
    step 2. Initialize a new Execution object for this run
    step 3. Use a uuid string as a file name for the temporary script name
    step 4. Create a run directory for the current run
    step 5. Get the commands entered by the user.  There are 2 ways to get the command history.       
       Way 1: use MATLAB’s Java internals to get the command history as a character array  
           (1) history = com.mathworks.mlservices.MLCommandHistoryServices.getSessionHisory;
           (2) use the command methodsview(com.mathwork.mlservices.MLCommandHistoryServices ) to check the methods for the internal java class MLCommandHistoryServices;

      Way 2: use prefer to get the preference folder, then search History.xml (for Matlab 2015a). Previous version may have different names, such as history.m    

In endRecord( ):
----------------------------
   step 1: Stop recording by setting the runManager.recording to be false
   step 2: Get submitter and MN node reference
   step 3: No need to generate yesworkflow image. Reason: no yw annotations there.
  (The following steps are the same for running a script )
   step 4: Record the ending time
   step 5: Save the metadata for the current execution 
   step 6: Serialize the execution objects to the local file system  
   step 7: Build a d1 data package

**Comment by sycao5** [comment]
It works so I close this task now. If enhancement is needed later, this ticket can be reopened.
