### ISSUE TITLE
Modify viewRun() to return a struct or cell array

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#163]
When a call is made to viewRun() and the output is assigned to a variable, the variable should be either a struct or cell array so that the information can be read programmatically.  Decide which structure is best based on the type of output (mixed text, numbers, dates). Write a unit test that calls the function and retrieves a portion of the output programmatically.

**Comment by sycao5** [comment]
Currently there is no data structure to store the output. The output is printed to stdout.

**Comment by mbjones** [comment]
The request here is to modify the structure and return the information in a data structure in addition to printing it on stdout. Reopening.

**Comment by csjx** [comment]
The `testView()` method in the RunManagerTest also doesn't programmatically test that certain values can be retrieved from the returned structure.  This needs to be added to the test.

**Comment by sycao5** [comment]
Change the signature of view(packageId, sequenceNumber, tag), instead of only using packageId.

**Comment by sycao5** [comment]
Include the packageId to the output of listRuns( )
