### ISSUE TITLE
Implement getMetadata and putMetadata() API methods in the Matlab client

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#166]
In the [Run Manager API](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-capture/Run-manager-API.rst), we have defined the getMetadata() and putMetadata() API methods.  These allow the researcher to view the metadata that has been created for a run, and to overwrite the existing metadata.  Implement these two methods, and modify the RunManager class to create basic template-based science metadata.
- [x] Create a science metadata template for runs
- [x] Create an EML class to load an existing EMl doc or mint a new one
- [x] Enable metadata replacement from Configuration parameters set by the researcher
- [x] Modify the RunManager to produce run-specific science metadata
- [x] Implement putMetadata()
- [x] Write a unit test for putMetadata()
- [x] Implement getMetadata()
- [x] Write a unit test for getMetadata()

**Comment by csjx** [comment]
functionality is working here - we just need unit tests written. Keeping this open until we can finish those.

**Comment by sycao5** [comment]
The unit tests are committed
