### ISSUE TITLE
Make Matlab unit tests atomic and handle a blank environment

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#168]
Many of the Matlab unit tests assume that some actions have already occurred, and so aren't standalone per se.  They also assume information is written to the executions database, when, in a blank (new) environment, that may not be the case.  Fix the unit tests to be standalone (i.e. build that data that are needed) and return the environment to its clean blank state.  For instance, for `testListRuns()`, write test runs to the executions database, then list them.  Once the test is complete, remove the runs from the executions database.

**Comment by sycao5** [comment]
ok

**Comment by csjx** [comment]
Hi @sycao5 - I've assigned this to myself because I'm working on it now.  I'll let you know when I'm done. Cheers.

**Comment by csjx** [comment]
These looks to be complete.  After removing ~/.d1 and running the test suite, tests are not failing due to a non-existent configuration directory. Closing.
