### ISSUE TITLE
Modify the Matlab Client listRuns() input and output

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#169]
The behavior of `listRuns()` is very close, but needs some modification.  
- [x] For input, `listRuns()` requires four parameters: `quiet`, `startDate`, `endDate`, and `tags`.  Change the input behavior such that none of these parameters are required and a researcher can just call `listRuns()`.  Use the `varargin` variable to handle these parameters as optional input.  We may need to consider using name/value pairs as input, like `listRuns('quiet', true, 'tags', 'my_tag').
- [x] For output, `listRuns()' is showing too many columns, and the table wraps even with a very large screen.  Reduce the table columns to just the following:
  * Number (the sequence number of the run)
  * Script ( the name of the script or model)
  * Tags
  * Start Date
  * End Date
  * Publish Date

The rest of the details can be shown in the `viewRun()` call, but this will give a quick, summarized view of the runs.

**Comment by sycao5** [comment]
ok

**Comment by sycao5** [comment]
completed
