### ISSUE TITLE
Create a Matlab DataONE Toolbox walk-through document

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#171]
For the 2015 ALl Hands Meeting, and potentially for future users of the toolbox, create a walk-through document that shows, step by step, how to install, configure, and use the Matlab DataONE Toolbox.  Use the MsTMIP C3C4 driver script as a concrete example.  Show how to use each of the Run Manager API functions to record, list, delete overall manage runs.  Show how to mark up a script using the YesWorkflow syntax, how to edit science metadata templates, and then how to publish the package to a DataONE Member Node.

**Comment by sycao5** [comment]
When  I call the following API, the savejson throws the following errors. The problem exists on mac and linux platform.

>> set(mgr.configuration, 'capture_yesworkflow_comments', false);
Error using savejson>mat2json (line 304)
input is not an array

Error in savejson>obj2json (line 163)
    txt=mat2json(name,item,level,varargin{:});

Error in savejson>struct2json (line 243)
	    txt=sprintf('%s%s',txt,obj2json(names{e},getfield(item(i,j),...

Error in savejson>obj2json (line 159)
    txt=struct2json(name,item,level,varargin{:});

Error in savejson (line 129)
json=obj2json(rootname,obj,rootlevel,opt);

Error in org.dataone.client.configure.Configuration/saveConfig (line 399)
            savejson('', configurationStruct, configuration.persistent_configuration_file_name);

Error in org.dataone.client.configure.Configuration/set (line 342)
            configuration.saveConfig();

**Comment by sycao5** [comment]
The following command will not work on mac OS.

[status, path] = system('which dot')

**Comment by csjx** [comment]
This is done, and can be found:
https://github.com/DataONEorg/matlab-dataone/blob/master/docs/walk-through.rst
