### ISSUE TITLE
Fix the testView() unit test in the Matlab Client

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#174]
The testView() test is failing because it assumes that that a fixed execution id is present, but doesn't create the execution dynamically.  It also doesn't make any assertions about the returned conent.

- [x] Create an Execution instance in the test and set the `execution_id` to the one expected. Use the `createFakeExecution()` function to write the execution to the database and to create the directory.
- [x] Call the `view()` function and return the results into an array, and use `assertEqual()` to be sure the view is correct with regard to the `execution_id`.
- [x] Do the same and assert that the sections returned in the detail view are correct.

**Comment by sycao5** [comment]
complete.
