### ISSUE TITLE
Fix Matlab Client RunManager incorrect setting of submitter DN string

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#176]
The RunManager class uses the CertificateManager class to grab the DN string from an X509 certificate, and adds it to the configuration:
```matlab
certificate = runManager.getCertificate();
% Pull the subject DN out of the certificate for use in system metadata
runManager.configuration.submitter = certificate.getSubjectDN().toString();
```
In doing this, it adds the string in reverse RDN order, like: 
`DC=org,DC=cilogon,C=US,O=Google,CN=Christopher Jones A2108`

This should be:
`CN=Christopher Jones A2108,O=Google,C=US,DC=cilogon,DC=org`

Ensure that the DN string is normalized after using `getSubjectDN()`.  IIRC, there's a method in `CertificateManager` to normalize DNs. Or do I?

**Comment by sycao5** [comment]
Done.
