### ISSUE TITLE
Add authentication token support to the Matlab Client

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#180]
The Matlab Client `publish()` method currently uses X509 certificate-based authentication.  Include support for the Bearer Token as described in the [DataONE architecture documents](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/design/Authentication.html#using-access-tokens). 
In `publish()`, if the `Configuration.authentication_token` property is set, use the token by calling `D1Client.setAuthToken()`.  If it's not set, check for the X509 certificate file and use it through the `CertificateManager.getInstance().loadCertificate()` call.  If neither are set, send an error to the user that one or the other need to be set before calling `publish()`.

You can test this functionality by logging into https://search.test.dataone.org and generating an authentication token in your profile.

**Comment by sycao5** [comment]
Done.
