### ISSUE TITLE
Summarize MsTMIP model input metadata

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#181]
Since the FGDC metadata provided by the MsTMIP MN for the standardized model input data don't include attribute-level metadata, I harvested the data to mn-stage-ucsb-4.test.dataone.org, and created NcML metadata files that include the entity and attribute metadata.  Mark needs this information in a summarized form like a CSV table.  
I've started code to produce a table with the following columns:
- netcdf_file_name
- dimension_name
- dimension_length
- dimension_is_unlimited
- variable_name
- variable_type
- variable_shape
- variable_value
- attribute_name
- attribute_value
- ncml_url

This should provide all of the CF metadata, units, etc. in a single file. This relates to #17 and #44.

**Comment by csjx** [comment]
It turns out that more than 50% of the NcML files are not well-formed XML due to a character pasted in to the original netcdf files that is in the Windows-1252 character set, not UTF-8.  I'm working on getting the character replaced in the byte stream, and then will be able to produce the CSV table.

**Comment by mbjones** [comment]
@csjx Bummer.  Any idea how this happened, given that Metacat should have rejected any non-well-formed documents during sync?

**Comment by csjx** [comment]
@mbjones Well, the NcML documents were never loaded into Metacat.  The task was to download all of the NetCDF data files and put them on a UCSB VM for easy access by Margaret and Mark, and to produce the NcML as a quick way to view attribute metadata.  Those are all at https://mn-stage-ucsb-4.test.dataone.org/mstmip. I just noticed the offending documents as I was producing this summary for @mpsaloha .

**Comment by mbjones** [comment]
@csjx Cool, that's great that we didn't find a bug in validation -- I thought the NcML files had been uploaded, but now I remember those were FGDC files for MsTMIP. Thanks for the clarification.

**Comment by csjx** [comment]
@mpsaloha, @mobb I've created a [CSV file](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/science-scenarios/example-files/mstmip/NetCDFSummary/mstmip-ncml-summary.csv) that summarizes the MsTMIP NetCDF data, and added it to our repo.  We can discuss this during our meeting Monday, or tomorrow if you'd like.  For defining ontology concepts, I'd expect you'd want to take a look at the variables with the `standard_name`, `long_name`, `description`, and `units` attributes.  Let me know if this is what you were thinking, or if we need to change something. Cheers.

**Comment by csjx** [comment]
Note: 46 of the 1483 NetCDF files had no metadata in the NcML files.  They are:
<pre>
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_Evap.nc4.ncml.xml
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_TotLivBiom.nc4.ncml.xml
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_NEP.nc4.ncml.xml
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_TotalResp.nc4.ncml.xml
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_GPP.nc4.ncml.xml
./VISIT/VISIT_RG1_Monthly/VISIT_RG1_Monthly_NEE.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_Tair.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_GPP.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_NEP.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_LAI.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_NEE.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_Evap.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_TotLivBiom.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_HeteroResp.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_NPP.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_TotSoilCarb.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_AutoResp.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_Rainf.nc4.ncml.xml
./VEGAS2.1/VEGAS2.1_SG2_Monthly/VEGAS2.1_SG2_Monthly_TotalResp.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_NPP.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_HeteroResp.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_NEP.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_AutoResp.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_SWE.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_TotSoilCarb.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_TotalResp.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_Fire_flux.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_TotLivBiom.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_NEE.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_Qs.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_GPP.nc4.ncml.xml
./TEM6/TEM6_SG2_Monthly/TEM6_SG2_Monthly_SoilMoist.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_NEP.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_AutoResp.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_TotLivBiom.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_SoilMoist.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_Fire_flux.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_Qs.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_GPP.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_TotSoilCarb.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_NPP.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_SWE.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_HeteroResp.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_Tdepth.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_NEE.nc4.ncml.xml
./TEM6/TEM6_BG1_Monthly/TEM6_BG1_Monthly_TotalResp.nc4.ncml.xml
</pre>
We'll need to do some digging on why.

**Comment by mobb** [comment]
Hi Chris -
thanks for the start on this! I think for the ontology development, we 
will need output of all the values for a variable, particularly the text 
in long_name and description, and units.
Is that easy to add? I glanced at a couple of xml files (eg 
https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Tair.nc4.ncml.xml) 
and it seems to be common. I didn't dig into the python to see how you 
did it, though.

Margaret

<variable name="Tair" shape="time lat lon" type="float">
     <attribute name="_FillValue" type="float" value="-9999." />
     <attribute name="description" value="Near surface air temperature" />
     <attribute name="long_name" value="Near surface air temperature" />
     <attribute name="units" value="K" />
     <attribute name="grid_mapping" value="crs" />
   </variable>

-----------
Margaret O'Brien
Information Management
Santa Barbara Coastal LTER
Marine Science Institute, UCSB
Santa Barbara, CA 93106
805-893-2071 (voice)
http://sbc.lternet.edu

**Comment by csjx** [comment]
Hi Margaret,
Yes, that's already in there.  The `attribute_name` column has the names like `long_name`, `units`, etc., and the `attribute_value` column has the text value for each corresponding name.  These are all associated with a given netcdf variable as well, so you'll see a `variable_name` column too.  This happens to be smaller than 65K rows, so you can actually open it in Excel or Numbers pretty readily.

**Comment by mobb** [comment]
Hi Chris -
Below is what I see in the file, though -- no label or descriptions.


head -1 mstmip-ncml-summary.csv | tr ',' '\12'
ï»¿netcdf_file_name
dimension_name
dimension_length
dimension_is_unlimited
variable_name
variable_type
variable_shape
attribute_name
attribute_value
ncml_url

-----------
Margaret O'Brien
Information Management
Santa Barbara Coastal LTER
Marine Science Institute, UCSB
Santa Barbara, CA 93106
805-893-2071 (voice)
http://sbc.lternet.edu

**Comment by csjx** [comment]
Hi Margaret,
I think I understand how I've miscommunicated the contents.  I'll try from a different angle:
This file is summarizing the components of the hierarchical **NetCDF file** itself, which include `dimensions`, `variables`, and `attributes`.  Each `variable` in the file can be seen as an entity (a table or a matrix), and may be 1,2, 3 dimensional etc., depending on the dimensions associated with it.  The file itself has `attributes`, and each variable also has `attributes` associated with it that are name/value pairs.  For instance, `long_name`, `description`, `units`, `reference`, etc., with their corresponding values.

So, this table is a summary of these NetCDF components, and I'd consider it a tall, not wide, table.  For instance, the `attribute_name` and `attribute_value` columns contain all of the information you're looking for, stacked vertically. Below is a `head -50` excerpt of the table (you'll need to scroll right on the [github page](https://github.com/DataONEorg/sem-prov-design/issues/181) to see the table rendered, it won't be formatted in email).

Mark had asked for a CSV dump of the metadata, and this was the only way I could see to organize the hierarchical information, since each file has different variables and attributes (although there's a bunch of repeats with time being the difference between files). Let's chat about how to filter this file so you get what you need.
 
Cheers,
Chris

netcdf_file_name|dimension_name|dimension_length|dimension_is_unlimited|variable_name|variable_type|variable_shape|attribute_name|attribute_value|ncml_url
----------------|--------------|----------------|----------------------|-------------|-------------|--------------|--------------|---------------|--------
CLM4_SG1_Monthly_Lwnet.nc4|time|1320|true||||||https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|lat|360|||||||https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|lon|720|||||||https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|nbnds|2|||||||https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||Conventions|CF-1.4|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||history|Standardized at ORNL (2014-06-20)|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||id|8bb29194-6b6e-422d-9e8f-be71e3e38b3e|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||title|CLM4 monthly Lwnet for MsTMIP SG1 global simulation|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||source|CLM-CN v4.0|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||model|CLM-CN|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||model_version|v4.0|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||contact|Daniel J. Hayes|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||institution|Oak Ridge National Laboratory|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||email|hayesdj@ornl.gov|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||references|"Oleson K. W. et al., 2010, Technical description of version 4.0 of the Community Land Model (CLM) NCAR Tech. Note NCAR/TN-478+STR (Boulder, CO: National Center for Atmospheric Research)"|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||project|Multi-scale Synthesis and Terrestrial Model Intercomparison Project (MsTMIP)|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||experiment|SG1|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||comment|"This research is supported in part by the US Department of Energy (DOE), Office of Science, Biological and Environmental Research. Oak Ridge National Laboratory is managed by UT-BATTELLE for DOE under contract DE-AC05-00OR22725.
Data files were standardized at the Oak Ridge National Laboratory (ORNL)."|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||timestamp|2014-08-09T17:56:31Z|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4|||||||mstmip_internal_version|v1.0.0|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||Lwnet|float|time lat lon|_FillValue|-9999.|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||Lwnet|float|time lat lon|description|Incident longwave radiation minus  simulated outgoing longwave radiation (positive into grnd)|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||Lwnet|float|time lat lon|long_name|Net Longwave Radiation|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||Lwnet|float|time lat lon|units|W m-2|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||Lwnet|float|time lat lon|grid_mapping|crs|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat|float|lat|units|degrees_north|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat|float|lat|long_name|Latitude|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat|float|lat|description|latitude at center of each grid cell|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat|float|lat|bounds|lat_bnds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat_bnds|float|lat nbnds|units|degrees_north|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat_bnds|float|lat nbnds|long_name|Latitude south-north bounds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lat_bnds|float|lat nbnds|description|"(south boundary of grid cell, north boundary of grid cell)"|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon|float|lon|units|degrees_east|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon|float|lon|long_name|Longitude|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon|float|lon|description|longitude at center of each grid cell|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon|float|lon|bounds|lon_bnds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon_bnds|float|lon nbnds|units|degrees_east|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon_bnds|float|lon nbnds|long_name|Longitude west-east bounds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||lon_bnds|float|lon nbnds|description|"(west boundary of grid cell, east boundary of grid cell)"|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|units|days since 1700-01-01 00:00:00 UTC|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|long_name|Time middle averaging period|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|calendar|proleptic_gregorian|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|description|julian days days since 1700-01-01 00:00:00 UTC for middle of time averaging period Proleptic_Gregorianc calendar|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|bounds|time_bnds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time|double|time|standard_name|time|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time_bnds|double|time nbnds|units|days since 1700-01-01 00:00:00 UTC|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time_bnds|double|time nbnds|long_name|Time beginning-end bounds|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
CLM4_SG1_Monthly_Lwnet.nc4||||time_bnds|double|time nbnds|calendar|proleptic_gregorian|https://mn-stage-ucsb-4.test.dataone.org/mstmip/CLM4/CLM4_SG1_Monthly/CLM4_SG1_Monthly_Lwnet.nc4.ncml.xml
