### ISSUE TITLE
Refactor org.dataone.client.v2 Matlab class layout

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#186]
To implement both the DataONE Member Node and Coordinating Node APIs, refactor the Matlab client code to be more in line with the Java client.  Create wrapper classes for D1Client, D1Object, D1Node, MNode, and CNode.  The return types of these classes' methods should be familiar to Matlab users, rather than Java return types.
- [x] Create a `DataONEClient` class
- [x] Refactor `D1Object.m` to `DataObject.m`
- [x] Create a `DataONENode` class
- [x] Create a `CoordinatingNode` class (subclass of `DataONENode`)
- [x] refactor the `MemberNode` class to subclass `DataONENode`
- [x] Create a `SystemMetadata` class

**Comment by sycao5** [comment]
For the listObjects() in MemberNode , where can I find the 'total' attribute value?

**Comment by csjx** [comment]
@yang - When you call the Java MN.listObjects, it will return an ObjectList instance.  The ObjectList has these three methods:
- getTotal()
- getCount()
- getStart()
It also has a method to get a List<ObjectInfo>, which has each object record in it.

**Comment by sycao5** [comment]
It works. Thanks

**Comment by sycao5** [comment]
The functions need to complete:

CoordinatingNode.listFormats()
CoordinatingNode.getFormat()
CoordinatingNode.listNodes()

**Comment by csjx** [comment]
From a refactor standpoint, this ticket is complete.  We still need to flesh out some API methods, particularly in the CoordinatingNode class, but the hierarchy is now in place and functional. Closing.
