### ISSUE TITLE
Enable drill-down browsing by subclasses of annotations 

### ISSUE THREAD

**Issue by leinfelder** [DataONEorg/sem-prov-design#216]
Instead of just showing search results for packages annotated with the same concepts, we can show a hierarchical list to allow exploration of search results by clicking subclasses. This would also be from the data package view, as an option in the drowdown menu from the tag pill button.

**Comment by lauren-palmer** [comment]
This is the hierarchical list that will show up in the dropdown list when searching or adding an annotation, correct?

**Comment by leinfelder** [comment]
I think this is like #215 in that it is rooted at the concept in the pill/button and only shows subclasses as possible next search links.

**Comment by leinfelder** [comment]
Now showing the BioPortal Tree widget in the dropdown menu. Clicking on a [sub]concept takes the user to a new search for that concept.
