### ISSUE TITLE
Expected annotations not showing up in UI

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-design#227]
@mobb just alerted me to what looks like a bug. For [this dataset](), the first Entity (`2002 Vegetation data.txt`) has an attribute `ACMO` that was manually annotated with the Measurement Type `<http://purl.dataone.org/odo/ECSO_00002146>` (Achyrachaena_mollis frequency). This class *does* appear in [the index](https://search-sandbox-2.test.dataone.org/cn/v2/query/solr/?q=id:Collinge.3.34&fl=identifier,sem_annotation) and the dataset *is* found when you do a semantic search from the Catalog.

The only thing that seems wrong is that a semantic annotation for this attribute doesn't appear in the UI:

![image](https://cloud.githubusercontent.com/assets/563/20160489/ba6d4ee4-a693-11e6-8b4a-f8ca51884955.png)

It seems like this isn't the only instance of this but I thought I'd share a specific example to help debug.

Any thoughts @leinfelder?

**Comment by leinfelder** [comment]
Yes, I commented on this in the epad but I'll say the same here. The manual annotations from the spreadsheet all use "PLACEHOLDER" as part of the selector rather than the attributeName value. All this is hidden in the UI, but the AnnotatorJS needs the correct string in the correct div in order to put the annotation in the right place (and then for us to make it pretty with more DOM manipulation).

I've updated the CN to include this string so you should now see all the annotations that were sourced from the spreadsheet.

**Comment by amoeba** [comment]
Thanks!

**Comment by amoeba** [comment]
Hrm, on investigation I'm not seeing any semantic annotations anymore. Is that expected?

**Comment by leinfelder** [comment]
![image](https://cloud.githubusercontent.com/assets/2955720/20165219/347b275c-a6c0-11e6-9ffe-9b3f32dd941e.png)

**Comment by leinfelder** [comment]
Let it sit for a bit and they'll load. 1100+ annotations on this one so it takes forever!

**Comment by amoeba** [comment]
Ahh! Thanks. Can the performance be improved right now so @mobb and @mpsaloha can look around and check things out or should they just stick to simpler datasets?

**Comment by leinfelder** [comment]
Unfortunately, I already added server-side caching. The annotations themselves are returned quite quickly (~3-5 sec depending on transfer speeds), but the AnnotatorJS library takes the rest of the time to actually find all the appropriate spots on the page for those 1149 annotations.

See how quickly the cached results come in: https://cn-sandbox-2.test.dataone.org/portal/annotator/search?uri=https://cn-sandbox-2.test.dataone.org/cn/v2/resolve/Collinge.3.34

**Comment by amoeba** [comment]
Gotcha. Thanks for the explanation.

**Comment by leinfelder** [comment]
There may have been an email to the annotatorJS list that mentioned this slowness, but I have not been able to find it or remember if there was even a hint at a possible solution to explore. So for now, perhaps stick with examples that are less heavily annotated.
