### ISSUE TITLE
Delete and Flag as incorrect links not working in annotation UI

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-design#231]
I logged in, added two (bogus) annotations to Goldengate2010.txt's `YEAR` attribute. When I hover over either of the bogus annotations I added, clicking the Delete button doesn't seem to change anything.

![screen shot 2017-02-15 at 10 25 14 am](https://cloud.githubusercontent.com/assets/563/22991668/91132bea-f369-11e6-8f16-df93d58ec988.png)

@leinfelder and I talked on Slack about this and I agreed to filing an issue.
@leinfelder also mentioned that he thinks you can only delete annotations if you're the owner of the metadata document

**Comment by amoeba** [comment]
I also need/want to remove my (now) three bogus annotations

- [ ] Remove atlantic_salmon_catch_per_unit_effort, Time Step, Agylla_divisa Count

**Comment by leinfelder** [comment]
Do you remember the PID of the package?

**Comment by amoeba** [comment]
^ Yeah I think so

**Comment by leinfelder** [comment]
Fixed this - listeners were not registered for some reason and there was an issue with the handler methods. Have not yet deployed on test server

**Comment by amoeba** [comment]
Great, thanks @leinfelder !
