### ISSUE TITLE
Annotations don't show up on the page after they're added

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/sem-prov-design#232]
It seems like annotations aren't immediately rendered on the page when they're added.

I...

- Logged in
- Browsed to https://search-sandbox-2.test.dataone.org/f/#view/peggym.1108.68
- Scrolled down to the `YEAR` attribute of `Goldengate2010.txt`
- Added an annotation of `Atlantic_salmon Catch_per_unit_effort`
- Waited 5-10 s
- Did not see my attribute added to the list
- Refreshed the page
- **Did** see the attribute in the list

![recording](https://cloud.githubusercontent.com/assets/563/22991910/6386bc9a-f36a-11e6-9434-12df816d71a3.gif)

**Comment by leinfelder** [comment]
Took quite a bit of sleuthing, but turned out it was because of a lack of annotationStored event - needed to add that to the Annotator library so we know when the annotation is fully saved and has an id. Basically there was a race condition with the existing annotationCreated event callback.

**Comment by amoeba** [comment]
Thanks for debugging and fixing!
