### ISSUE TITLE
Example provOne instance documents

### ISSUE THREAD

**Issue by smrgeoinfo** [DataONEorg/sem-prov-design#241]
I'm looking for example instance documents using the provOne vocabulary to describe some provenance traces to better understand the intended implementation.  I found one example (#239 sycao5 2017-05-04), is this consistent with  current model? Are there other examples?  Thanks

**Comment by sycao5** [comment]
Hi,

The example #239 was a simple practice example one year ago. If you have questions about this example, I am happy to help you. 

Thanks,
Yang

**Comment by mbjones** [comment]
Thanks, @sycao5 .  We have a bunch of real world examples now in the repository, so its probably best to use those.  I added an example [TTL file from Rickett's data set](https://github.com/ESIPFed/Earth-Data-Provenance-Workshop/blob/master/example-instances/dataone-prov-example.ttl), but others can be found on https://search.dataone.org.

**Comment by smrgeoinfo** [comment]
hmmm, its not at all apparent how to use dataone search to find records that have PROV, or once found, how to get the serialized PROV,

**Comment by amoeba** [comment]
Hey @smrgeoinfo you're right. Datasets with provenance information will have a special icon in the search results but I can't see a way to filter them. You'll have to roll your own approach for now:

1. Which types of provone relationships are you interested in? Find the property of interest in [this list](https://cn.dataone.org/cn/v2/query/solr) (search for `prov_`). e.g., `prov_wasDerviedFrom`
2. Search our search index directly like this. e.g., Search for Objects (files) that are involved in `prov_wasDerivedFrom` statements: https://cn.dataone.org/cn/v2/query/solr/?q=prov_wasDerivedFrom:*&fl=resourceMap&rows=10
3. For any `resourceMap` values in the results, you can grab the RDF/XML. e.g., Grab the RDF/XML for the first result on the above page: http://cn.dataone.org/cn/v2/resolve/urn:uuid:1dced450-d07f-42e9-8c47-58724c75412b

Give that a whirl and let us know if that works for you and for your use case.

**Comment by smrgeoinfo** [comment]
@amoeba thanks, that gives me a way to find the Prov
