### ISSUE TITLE
Publish version 1 ontologies to ontology repository

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#49]
Current ontologies for MsTMIP and LTER are being edited in GitHub here:

https://github.com/DataONEorg/sem-prov-ontologies

These should be added to the ontology repository so they are accessible programmatically via the ontology search API.

**Comment by leinfelder** [comment]
We will have two ontology repositories for dev/testing phase: BioPortal and ESOR. Both these repositories should have all/only the ontologies we have decided to use for our annotation purposes:
- D1-CARBON-FLUX
- PROV-O
- PROV-ONE
- DATA-CITE
- ENVO
- Dublin Core
- ChEBI

**Comment by leinfelder** [comment]
So far, all but Dublin Core have been added to BioPortal for evaluation.

**Comment by leinfelder** [comment]
all are in BioPortal now and being used in the UI for annotation suggestions

**Comment by mobb** [comment]
HI Ben
Can you confirm that the ontology can use annotation properties for 
synonyms in SPARQL queries?

specifically, we want to use these two annotation props:
has_Related_Synonym
has_Near_Synonym

Only 2 classes have these so far (for testing, below), but I'd like to 
add scads more this week.

Leaf Litter Carbon Pool
http://www.semanticweb.org/ontologies/2014/10/D1_CarbonFlux#OWLClass_cd5f0ef4_2990_4d4d_914a_30b6f8985b5b

Leaf Carbon Pool
http://www.semanticweb.org/ontologies/2014/10/D1_CarbonFlux#OWLClass_76b459c6_1fa9_4274_9ba8_c089405d82f9

Thanks,
Margaret
------------

**Comment by leinfelder** [comment]
I''d be happy to. But please update your ontology in web protege so that you don't keep overwriting my change to the URI.
We are using this value so that it can be resolved by things like BioPortal, ESOR, our UI, etc:
https://purl.org/dataone/ontologies/observation/D1_carbon_flux_1.owl

Just committed this to github again, so that should be the latest version (with your recent changes).

Thanks!
-ben

**Comment by leinfelder** [comment]
Looking into this, I see that the has_Related_Synonym annotation property is actually defined in a webprotege namespace: http://webprotege.stanford.edu/RDPR2w0tyuMjcOslIygEemk
Is this intentional?
-ben
