### ISSUE TITLE
Review design and use of OA as annotation model

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#50]
The [current architecture proposal](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/use-cases/semantics/semantic-annotation.md) for semantic search calls for the use of the Open Annotation ontology along with PROV and OBOE to accomplish annotation of data attributes using vocabulary from OBOE and PROV.  We need to review and finalize this design, ensuring that all partners are in agreement on the approach using selectors against metadata documents as the main way to attach annotations to particular data objects in DataONE.

**Comment by leinfelder** [comment]
At the 20150223 sem-prov meeting we agreed to move forward with AnnotatorJS model and then transition to OA when their tool supports it.
