### ISSUE TITLE
Update the ProvONE ontology and documentation

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#53]
Modify the ProvONE OWL Ontology to match the changes we've made while modifying the ProvONE UML diagram. Also update the HTML documentation with new class names, property names, and their definitions.

**Comment by csjx** [comment]
The HTML is updated, and is available for review:
https://cn-sandbox-2.test.dataone.org/sem-prov-ontologies/provenance/ProvONE/v1/provone.html
