### ISSUE TITLE
Formalize the YesWorkflow comment syntax

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#54]
Develop the YesWorkflow comment syntax by formalizing it in an EBNF specification.  Current work on this has been started in [Google Docs](https://docs.google.com/a/nceas.ucsb.edu/document/d/16320aNsDgvanDVsjkm8Kj0p9afVAocril8dS8_mtYxc/edit). Relates to [Use Case 41 - Document Script](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/use-cases/provenance/use-case-41-Document-Script.rst).

**Comment by sycao5** [comment]
@csjx @PaoloMissier @mbjones  @tmcphillips 

Can we close this issue now? If not, what the remaining work or difficulty need to complete?

**Comment by csjx** [comment]
@sycao5 As Tim had mentioned in [YW Issue 31](https://github.com/yesworkflow-org/yw-prototypes/issues/31#issuecomment-165293958), he has drafted a [language reference](https://github.com/yesworkflow-org/yw-prototypes/wiki/Language-Reference) based on the EBNF Google Doc.  While this is a good start, this language reference should be updated with **definitions** of each of the keywords.  I'd also turn the specification into a markdown table for easier reading.  Either way, will you close this task, and open a new task in the YW project, and take a pass at reformatting the table and adding definitions? Thanks.

**Comment by mbjones** [comment]
Closing this task as it is really part of the YW project now.
