### ISSUE TITLE
create matlab UI mockups for provenance functionality

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#55]
The Matlab system will be modified to add functions for tracking and recording provenance relationships, and for displaying those relationships.  We need user interface mockups of the use of matlab for:

- [ ] starting and stopping provenance recording
- [ ] viewing a list of provenance records
- [ ] viewing the details of a provenance trace, including the data relationships
- [ ] uploading a provenance trace to DataONE Member Nodes

**Comment by sycao5** [comment]
@csjx @lauren-walker @mbjones @gothub 

Do we need this issue to represent the requirement for local provenance capturing and management tool?

**Comment by sycao5** [comment]
We have adopted the similar Matlab user interface for provenance functionalities as R package. This issue can be closed.
