### ISSUE TITLE
Define an abstract 'matching service API'

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#56]
Define an abstract 'matching service API'. This represents the service that will be called whenever part of the annotation system needs to establish a match between some natural language metadata and a specific set of concepts from one or more ontologies.  The API signature should take natural language metadata fields as input, and return a list of matching ontology URIs with associated scores indicating the effectiveness of the match.  

There might be several versions of this API call.  The simplest would be something like:
```C
getMatchingConcepts(metadata[])::{term, score}
```

This has the advantage of simplicity, but doesn't allow the matching algorithm to use any of the semantic information found in typical metadata standards (such as unit definitions).  So, a more specific API that passes in specific types of metadata might be:
```C
getMatchingConcepts(attributeNameText, attributeDefinitionText, attributeUnitText)::{term, score}
```
Other variants are possible.  Ultimately, the API should be able to be used to delegate to multiple different matching algorithms, starting with the simple BioPortal term-matching algorithm, and continuing with more sophisticated algorithms. The `score` value needs a common definition (possibly 0 to 1, where 1 is a perfect match).

To close this task, provide a design document in RST syntax that that defines the matching algorithm(s) API and follows the [DataONE API documentation conventions](http://jenkins-1.dataone.org/jenkins/job/API%20Documentation%20-%20trunk/ws/api-documentation/build/html/apis/MN_APIs.html#MNCore.getLogRecords).

**Comment by XixiLuo** [comment]
https://github.com/DataONEorg/sem-prov-design/blob/master/docs/api/annotatorAPI.rst

**Comment by leinfelder** [comment]
Reviewing the additions to the ConceptMatcher interface, I'm not sure about introducing a custom query syntax -- "keyword(type;type)" -- but at least there is still an option for just sending in a plain old string (or I hope so!)
