### ISSUE TITLE
Create method to call bioportal matching algorithms

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#58]
Implement the API described in issues #56 and #57 specifically for the BioPortal text matching algorithm.  This implementation would be in Java code that responds to the API defined in #56 and delegates to Bioportal to execute the matching algorithm.

I think @leinfelder has prototype code that does this already.

Implementation code for this should be placed in the [DataONEorg/annotator](https://github.com/DataONEorg/annotator) repository.

**Comment by leinfelder** [comment]
This is implemented in  org.dataone.annotator.matcher.bioportal.BioPortalService
