### ISSUE TITLE
Implement and test the D1Client class in Matlab

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#64]
Based on the functionality provided by the D1Client Java class, implement the Matlab-based wrapper class, and write unit tests that exercise the major methods (get(), getSystemMetadata(), create(), update(), etc.). Prioritize methods that will be used in the RunManager class to support provenance capture.

**Comment by csjx** [comment]
I'm closing this since we are using the Java D1Client to do the work in the publish() method of the RunManager class.
