### ISSUE TITLE
Create example provenance traces

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#65]
To test the provenance model itself, as well as indexing and search API, we need example traces that can be produced before the client tools in issue #64 are completed.  We need on the order of 10 provenance traces, that should be serialized as part of a data package ORE document and that use the ProvONE model for its vocabulary.

**Comment by csjx** [comment]
Test resource maps with provenance statements are now available here:
https://github.com/DataONEorg/sem-prov-design/tree/master/docs/science-scenarios/example-files/mstmip/ResourceMaps
