### ISSUE TITLE
Extend CN.query API for provenance queries

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#68]
Examine the existing CN query API and determine if any extensions are needed for typical provenance queries to satisfy our [provenance use cases](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/use-cases/provenance/use-cases-summary.rst).  Implement any changes that are needed (possibly under new tickets depending on their scope).

Part of this evaluation is deciding whether to use SOLR3 or SOLR4 query syntax for provenance queries in the web UI and client.

**Comment by csjx** [comment]
We've decided that the Solr API satisfies our current needs and that we don't need to extend the search capabilities. Solr4 is also incorporated into the d1_cn_index_processor component, so we have the ability to take advantage of its features if need be. Closing this task.
