### ISSUE TITLE
Move RDF/XML subprocessor from Metacat to d1_cn_index_processor

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#74]
Ben has already worked on a generic RDF/XMl subprocessor for handling semantic annotations in Metacat.  Move this code into d1_cn_index_processor as a general RDF/XML subprocessor for both semantic annotations and provenance traces.  Work with Ben (and likely Skye) on this.

**Comment by leinfelder** [comment]
This was done earlier this week. The application-context-oa.xml should be updated to reflect desired PROV fields to be extracted, but that's a topic for another issue.
