### ISSUE TITLE
Extend the RDF/XML processor to extract provenance fields

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#75]
The RDF/XML subprocessor Ben has written currently loads annotation statements into a temporary store and issues SPARQL queries to extract semantic annotation field values for populating the Solr index.  Extend this to include the SPARQL queries needed to extract provenance trace fields to be populated in the Solr index. See #66.

**Comment by leinfelder** [comment]
This could be another instance of the RDF/XML subprocessor configured with queries to extract the desired fields or it could be lumped into one instance that including anything and everything we might expect to extract from an RDF/XML object [formatId]

**Comment by csjx** [comment]
I've added a provRdfXmlSubprocessor instance of the RDF/XML processor that supports the indexing of the fields listed in #66.
