### ISSUE TITLE
Incorporate YesWorkflow work into a Java library

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#78]
The [YesWorkflow prototype](https://github.com/yesworkflow-org/yw-prototypes) tool is a Java project that extracts inline comments of scientific analysis scripts and produces graph visualizations and provenance statements using the ProvONE model.  We need to formalize this work into a Java-based library for use in other applications, particularly the [DataONE Matlab Toolbox](https://github.com/DataONEorg/matlab-dataone).  This needs design work and further tickets for the details.

**Comment by sycao5** [comment]
The yes workflow java library can be downloaded from here:
https://github.com/yesworkflow-org/yw-prototypes#3-download-the-yesworkflow-jar-file

**Comment by csjx** [comment]
The YesWorkflow jar file can certainly be used. For this task, we'll need to include this jar file as a Maven dependency in the d1_libclient_java project.  To do this, either the YesWorkflow project should be registered in Maven Central, or we should create a DataONE Jenkins build such that the artifacts are available at maven.dataone.org.  
I'll assign this to Bertram @ludaesch to look into the Maven central prospects with @tmcphillips.  If that's not possible, assign this back to @csjx to deal with the Jenkins config.

**Comment by ludaesch** [comment]
Thanks Chris.

I'm cc-ing Tim on this so he can look into this.

Thanks, cheers,

Bertram


On Fri, Mar 6, 2015 at 10:35 AM, Christopher Jones <notifications@github.com

**Comment by csjx** [comment]
@sycao5 - Hi Yang,
As we discussed with Tim, the YesWorkflow jar artifacts are now available in SNAPSHOT versions in Maven Central.  To use the YW classes in the Matlab RunManager, we nee the jar incorporated into the d1_libclient_java library (at the trunk).  Please go ahead and add it ass a dependency.  The code is in the [DataONE Subversion repository](https://repository.dataone.org/software/cicore/trunk/d1_libclient_java/), so please coordinate with Matt (@mbjones) or Dave (@vdave) for write access to SVN.  Once the jar is a dependency in the POM, it should automatically build on the [Jenkins build server](http://jenkins-1.dataone.org/jenkins/job/d1_libclient_java/).  After a successful build, you can download the [latest 2.0.0 libclient jar with dependencies](http://maven.dataone.org/org/dataone/d1_libclient_java/2.0.0-SNAPSHOT/?C=M;O=D), and then update the [matlab-dataone/lib/java](https://github.com/DataONEorg/matlab-dataone/tree/master/lib/java) with the new (YW) jar and any changed dependency jars.  After the libraries are committed, you can then use them in the RunManager code to call YW classes.

**Comment by mbjones** [comment]
@csjx Hi Chris --  I wonder whether we should make d1_libclient_java directly depend on the YW jars, as there may be situations to use libclient without the YW provenance stuff.  It may be better to have the YW depend on d1 libclient for its serialization and resource map classes, rather than vice versa.  Have you talked about the dependency chain and keeping the dependencies light?  I see three possible scenarios:

1. d1_libclient imports yw
    Pros: universally available; Cons: increased dependencies, lack of modularity
2. yw imports d1_libclient
    Pros: d1_libclient stays independent, smaller; Cons: yw not universally available
3. Matlab `recordr` imports both d1_libclient and yw
   Pros: modular, few dependencies; Cons: harder to call, need glue layer that imports both libs

Just throwing this out there for consideration.  I'm not sure which is the best path.

**Comment by csjx** [comment]
@mbjones  - Hey Matt,
Yup, Tim and Yang and I discussed the dependency chain in particular.  It sounds like both projects (yes-workflow and d1_libclient_java) want to stay light.  In that case, I think your third option is the best.  We can just import both jars into the Matlab Toolbox, and call the classes as needed.  If there's no objection to that, I'll change the task description above to reflect it.

**Comment by tmcphillips** [comment]
For what it's worth, the YW jar including dependencies currently is 396KB (76 KB without dependencies).  YW depends directly on Snakeyaml (yaml reading/writing library, has no dependencies) and JOpt-simple (command-line parsing, depends only on Java Hamcrest), and I don't expect the core YW library/CLI project and jars to have too many more dependencies in the future (ideally none).  The future YW gui can go in a separate yw-gui maven project (yielding a larger standalone jar), and a distribution of YW enhanced with DataONE features and dependencies could be the product of a third maven project.

**Comment by sycao5** [comment]
The project pom.xml is now configured to push snapshot versions to Maven Central when the 'deploy' command is used. The snapshots can be browsed here .

The current snapshot version can be referred to in other Maven projects by adding this dependency:

<dependency>
    <groupId>org.yesworkflow</groupId>
    <artifactId>yesworkflow</artifactId>
    <version>0.2-SNAPSHOT</version>
</dependency>
