### ISSUE TITLE
clarify ProvONE Program is subclass of Entity

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/sem-prov-design#81]
The current ProvONE model diagram does not show `provone:Program` as a subclass of `prov:Entity`, which it should be.  Add the subclass arrow to the diagram, and determine if `provone:Program` should be changed to the same color as other `prov:Entity` classes.

- [ ] Update diagram
- [ ] Check that the corrects subclass axioms are in the OWL model

**Comment by csjx** [comment]
My understanding is that the ProvONE model diagram includes certain associations to highlight, and excludes others to keep the diagram simple.  Adding in the subclass arrow from `provone:Program` to `prov:Entity` opens the question about the other relationships:
<pre>
:provone:Program
    a prov:Plan
:provone:User
    a prov:Agent
:provone:Execution
    a prov:Activity
:provone:Controller
    a prov:Entity
</pre>

So, I would be in favor of leaving these arrows out, or perhaps using UML stereotype labels if it's important to convey the typing of each class in the diagram.

**Comment by csjx** [comment]
Closing this since the number of arrows (to be consistent) would be prohibitive.
