### ISSUE TITLE
Retrieve provenance during searches in the Search View 

### ISSUE THREAD

**Issue by lauren-walker** [DataONEorg/sem-prov-design#83]
We will need to design a Solr query that will retrieve provenance on the data package level. Since search results are displayed as data packages or science metadata, the query will be faster if the Solr documents for data packages (resource maps) have some or all of the provenance index fields, i.e. indexing provenance on the data package level.

The following provenance index fields will be retrieved:

- wasDerivedFrom
- generatedByProgram
- generatedByExecution
- usedByProgram
- usedByExecution
- usedByUser
- generatedByUser
- wasExecutedBy

Note that wasAssociatedWith will not be retrieved during a search unless the user specifically filters by that field. That particular provenance relationship by itself doesn't say whether a data package has "parents/sources" or "children/derivations."

**Comment by sycao5** [comment]
The requirement for "Retrieve provenance" has been implemented in DataONE Search. Close this issue.
