### ISSUE TITLE
Design and review plain-English provenance statements

### ISSUE THREAD

**Issue by lauren-walker** [DataONEorg/sem-prov-design#86]
We will need to translate the provenance found in the Solr index into plain-English sentences that scientists can understand. These should be reviewed by the Usability team to ensure they make sense.

Some examples:

(When viewing metadata about a data table):
(About a data table): "This data was used by the program X to generate the data you are currently viewing (Y)"
(About a figure): "This image was generated by the program X using the data you are currently viewing (Y)"

See the Metadata View mockups for more: https://github.com/DataONEorg/sem-prov-design/blob/master/docs/Web-UI-mockups/MetadataView/MetadataView-Hover.png

**Comment by sycao5** [comment]
@lauren-walker @csjx 

Can we close this issue now?

**Comment by sycao5** [comment]
Using plain English for provenance trace on DataONE Search has been implemented. So close this issue.
