### ISSUE TITLE
Add object file names to the index for display in the UI

### ISSUE THREAD

**Issue by lauren-walker** [DataONEorg/sem-prov-design#89]
When the web UI will be references other DataONE objects in the provenance statements, it will be helpful to the user to have a name or title for every object instead of an ID, which can be verbose and unidentifiable.

**Comment by sycao5** [comment]
@lauren-walker @csjx 
Can we close this issue now? If not, what the remaining work need to complete?

**Comment by csjx** [comment]
@lauren-walker @sycao5 So I think this is resolved since we are using the V2 API classes, and in particular `SystemMetadata` where we are populating the `fileName` field. This field is indexed by Solr. Please close if you agree Lauren.

**Comment by sycao5** [comment]
The file name is stored in 'SystemMetadata'. Close this issue.
