### ISSUE TITLE
Assemble test corpus for discovery, MNs for LTER, populate with measurement-level metadata

### ISSUE THREAD

**Issue by mobb** [DataONEorg/sem-prov-design#90]
Datasets to be copied from production TBD. Possibly, the initial population will to copy a subset of LTER sites' metadata records in D1

**Comment by mobb** [comment]
The data can be copied from this server:
https://cn-sandbox.test.dataone.org

Possibly, this server (cn-sandbox) could be used directly, if its integrity (and content) can be assured.

**Comment by leinfelder** [comment]
We have many development member nodes already and many of them are populated with the KNB and LTER data. For example, dev.nceas.ucsb.edu has  ~119525 objects on it (a few months old dump of the production KNB). Currently, that development node is registered in the cn-stage-2 environment (https://cn-stage-2.test.dataone.org/cn/v1/node/urn:node:mnTestKNB).
We could just register it in our dedicated sem-prov environment and be done with this task.

**Comment by mobb** [comment]
sounds fine to me. 
But I need to confirm that I got that server right before we proceed. I have to follow up.

**Comment by mbjones** [comment]
We talked with Mark Servilla about this today.  He indicated they are ready to register their new test MN that has PASTA data in a STAGE environment. So the proposal this morning was to register that in SANDBOX-2 instead so that it can used to both do the final test for LTER's GMN before they go production and to serve as the main test repository for semantics and provenance testing.  So, it seems we don't need a new node per se, and should probably retitle this ticket to reflect the registration task.

**Comment by mobb** [comment]
https://cn-sandbox.test.dataone.org is correct.

Can someone (?Chris, maybe) give us the name of the test server for the mstimp member node so we can start hitting that one, too. I can't find an issue dedicated to that.

**Comment by mbjones** [comment]
Its actually in Sandbox-2.  The list of nodes for any given CN is available, such as:

https://cn-sandbox-2.test.dataone.org/cn/v1/node

You can of course search using the ONEMercury UI in Sandbox-2 to look at the MsTMIP content.

https://cn-sandbox-2.test.dataone.org

**Comment by mobb** [comment]
thanks. I see some mstmip records in cn-sandbox-2.test.dataone.org, and no LTER records yet. I know the basic status of LTER. but have a question about MsTMIP

Are the MsTMIP records stable and representative of what MsTMIP will be contributing to production?
If no, what is anticipated timeline?

**Comment by mobb** [comment]
we might need to rename this issue: something like "assemble test corpus for discovery", since it now seems to cover both mstmip and lter. Unless we see those two needs as separate.

**Comment by csjx** [comment]
The MsTMIP MN will remain deployed in Sandbox2 only (not production) because of data access concerns.  So, yes, I'd say the MsTMIP records in Sandbox2 are stable and representative.

**Comment by mobb** [comment]
I guess I asked the wrong question. We'd like to have MSTMiP records with measurement-level metadata but haven't found any on cn-sandbox-2. When will it be there?

**Comment by csjx** [comment]
Ah, I see what you mean.  The ONEMercury search has a bug in it at the moment and it is showing the production node list, but if you try:
<pre>
https://cn-sandbox-2.test.dataone.org/cn/v1/query/solr/?q=*:*%20AND%20datasource:%22urn:node:mnTestMSTMIP%22
</pre>

That shows all of the harvested MsTMIP objects.  Point taken that none of them have measurement-level metadata. Sooo, this is a question for @yaxingwei . Yaxing, can you update the MsTMIP science metadata files to include entity and attribute level metadata?

**Comment by mobb** [comment]
In cn-sandbox-2, the LTER datasets are now contributed by the pasta GMN. So their IDs should be stable.

**Comment by mobb** [comment]
Split this ticket into 2: one each for the LTER and MsTMIP projects.
The LTER half of the work is done, so this issue can be closed.

**Comment by mobb** [comment]
There might be some LTER records in cn-sandbox-2.test.dataone.org that need to be purged.  All records coming from LTER GMN should be "with data". In search.test.dataone.org, checking this box: "staging test for PASTA GMN" yields 30940 results
checking the box "only include datasets with data" yields 21192 results, so the difference (~9000) might be from the older metacat MN, and should be purged before we run query tests.

reopening this issue.
