### ISSUE TITLE
Review the ProvONE hadEntity and had[In|Out]Port object properties

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#93]
The current [ProvONE model documentation](https://purl.dataone.org/provone-v1-dev) and the [model diagram](https://github.com/DataONEorg/sem-prov-ontologies/blob/master/provenance/ProvONE/v1/uml/provone-model.pdf?raw=true) show how we use the `prov:qualifiedUsage` and `prov:qualifiedGeneration` properties to further describe how a `prov:Entity prov:wasGeneratedBy provone:Execution` and how a `provone:Execution prov:used prov:Entity`.  We are explicitly trying to describe how the data bound to a given `provone:Port` of a `provone:Program` is used in the `provone:Execution`.  A [graph instance example diagram](https://github.com/DataONEorg/sem-prov-ontologies/blob/master/provenance/ProvONE/v1/examples/Provenance-instance-example-two-runs.pdf?raw=true) shows the current model being used.
The issues at hand are:
- Can/should `provone:hadEntity` be replaced with `prov:entity`?
- Can/should `provone:hadInPort` be replaced with `prov:hadUsage` coupled with `prov:hadRole`?
- Can/should `provone:hadOutPort` be replaced with `prov:hadGeneration` coupled with `prov:hadRole`?

Issues arise with the given domain and range of these PROV properties, particularly in relation to the `prov:Generation` class in the ProvONE model.  Also, do we even *need* `provone:hadEntity`?  The `prov:Entity` being described is already stated in the `prov:used` and `prov:wasGeneratedBy` statements .

**Comment by mbjones** [comment]
We held a conference call and resolved these issues, and Chris has incorporated the changes in to the new model in Github. Chris, please close this if you concur.
