### ISSUE TITLE
Change wasExecutedBy Solr field to hadExecution

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#97]
In issue #66, we debated about the correct name for indicating that a particular `provone:Program` had been executed and produced results.  We had both `wasExecutedBy` and `hadExecution` in the example.  To me, `wasExecutedBy` does not resonate semantically, and so I modified #66 to use `hadExecution`.  Update the [PROV Annotation design document ](https://github.com/DataONEorg/sem-prov-design/blob/master/docs/PROV-annotation-model/PROVmodel.md) to reflect this change.

**Comment by mbjones** [comment]
@csjx Interesting.  For me, `hadExecution` doesn't resonate, as it is more generic and not as clear that an `Execution` is an `Activity` and not an `Entity`.  I would use 'hadFoo' whenever `Foo` is an entity, and 'wasFooedBy` any time that `Foo` is an activity.

**Comment by csjx** [comment]
Will change this to prov_wasExecutedBy, after discussion with Ben, Lauren, and Peter.

**Comment by sycao5** [comment]
prov_wasExecutedByExecution is not in current resource map example. Does resource map contain the workflow-plane prov information or trace-plane prov information?

**Comment by csjx** [comment]
Yang, to just clarify this, we are renaming **Solr** index fields here, not PROV or ProvONE properties, so none of these fields need to be present in the resource maps.  The resource maps express relationships among Entities, Executions, Programs, Users, etc., and the Coordinating Nodes traverse the graphs and index particular combinations of relationships.  So, the above two comments will only change the names found in the Solr index for querying via clients like the web UI.

**Comment by csjx** [comment]
Done.
